defmodule AiPersonalChef.Repo.Migrations.Resources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add(:id, :text, null: false, primary_key: true)
    end

    create table(:posts, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:text, :text)
    end

    create table(:post_tags, primary_key: false) do
      add(:position, :bigint)

      add(
        :post_id,
        references(:posts,
          column: :id,
          name: "post_tags_post_id_fkey",
          type: :bigint,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )

      add(
        :tag_id,
        references(:tags,
          column: :id,
          name: "post_tags_tag_id_fkey",
          type: :text,
          prefix: "public"
        ),
        primary_key: true,
        null: false
      )
    end
  end

  def down do
    drop(constraint(:post_tags, "post_tags_post_id_fkey"))

    drop(constraint(:post_tags, "post_tags_tag_id_fkey"))

    drop(table(:post_tags))

    drop(table(:posts))

    drop(table(:tags))
  end
end
